app:
  cors:
    allowed-origins: "https://km0-front-prod.onrender.com"

  frontend:
    base-url: "https://km0-front-prod.onrender.com"

  backend:
    base-url: "https://km0-back-prod.onrender.com"