server:
  port: 8080
  
app:
  cors:
    allowed-origins: "http://localhost:4200"
  frontend:
    base-url: "http://localhost:4200"
  backend:
    base-url: "http://localhost:8080"    

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/km0dev
    username: admin
    password: pB55v1Ks?AxB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          strava:
            client-id: 179949
            client-secret: c60e34f786519935d4da649516af780ecec5b48a
            scope: activity:read_all
            token-name: access_token
            authentication-scheme: query
            client-authentication-scheme: form
            client-authentication-method: post
            client-name: Strava
            redirect-uri: "${app.backend.base-url}/exchange_token"
            authorization-grant-type: authorization_code
        provider:
          strava:
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id