app:
  cors:
    allowed-origins: "https://km0-front-rec.onrender.com"

  frontend:
    base-url: "https://km0-front-rec.onrender.com"

  backend:
    base-url: "https://km0-back-rec.onrender.com"

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
